'use client'

import { Button } from '@/components/ui/button'
import { ScrollArea } from '@/components/ui/scroll-area'
import { ArrowLeft, Archive, Share } from 'lucide-react'
import Link from 'next/link'
import { useSearchParams } from 'next/navigation'
import { useState, useEffect } from 'react'
import { ChatComposer } from '@/components/chat-composer'
import { ChatMessage } from '@/components/chat-message'

interface Message {
  role: 'user' | 'assistant'
  content: string
  model?: string
  hasSources?: boolean
}

export default function CodexChatPage() {
  const searchParams = useSearchParams()
  const prompt = searchParams.get('prompt') || 'Build a new feature'
  const [messages, setMessages] = useState<Message[]>([])

  useEffect(() => {
    const userMessage: Message = {
      role: 'user',
      content: prompt,
    }
    
    const aiResponse: Message = {
      role: 'assistant',
      content: `I'll help you ${prompt.toLowerCase()}. Let me analyze the requirements and create a solution for you.\n\nFirst, I'll examine the current codebase structure and identify the best approach. Then I'll implement the necessary changes while following best practices and maintaining code quality.\n\nThe implementation will include proper error handling, type safety, and comprehensive testing to ensure everything works as expected.`,
      model: 'GPT-4',
    }

    setMessages([userMessage, aiResponse])
  }, [prompt])

  const handleSubmit = (content: string) => {
    const newUserMessage: Message = { role: 'user', content }
    setMessages(prev => [...prev, newUserMessage])
    
    setTimeout(() => {
      const demoAssistantMessage: Message = { 
        role: 'assistant', 
        content: `This is a demo response to: "${content}". In a real application, this would be generated by the AI model with specific code changes and implementation details.`,
        model: 'GPT-4'
      }
      setMessages(prev => [...prev, demoAssistantMessage])
    }, 1000)
  }

  return (
    <div className="flex h-screen flex-col bg-black dark">
      <div className="flex h-[53px] items-center justify-between border-b border-zinc-800 bg-black px-4">
        <div className="flex items-center gap-3">
          <Link href="/codex">
            <Button variant="ghost" size="icon" className="h-8 w-8 text-zinc-400 hover:text-zinc-100">
              <ArrowLeft className="h-4 w-4" />
            </Button>
          </Link>
          <div>
            <h1 className="text-sm font-medium text-zinc-100">{prompt}</h1>
            <p className="text-xs text-zinc-500">
              {new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
            </p>
          </div>
        </div>
        
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="sm" className="h-8 gap-2 text-xs text-zinc-400 hover:text-zinc-100">
            <Archive className="h-3.5 w-3.5" />
            <span className="hidden sm:inline">Archive</span>
          </Button>
          <Button variant="ghost" size="sm" className="h-8 gap-2 text-xs text-zinc-400 hover:text-zinc-100">
            <Share className="h-3.5 w-3.5" />
            <span className="hidden sm:inline">Share</span>
          </Button>
        </div>
      </div>

      <ScrollArea className="flex-1">
        <div className="py-4">
          {messages.map((message, index) => (
            <ChatMessage key={index} {...message} />
          ))}
        </div>
      </ScrollArea>

      <ChatComposer 
        placeholder="Request changes or ask a question" 
        onSubmit={handleSubmit}
      />
    </div>
  )
}
