"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { Archive, ArrowLeft, Share } from "lucide-react";

import { ChatComposer } from "@/components/chat-composer";
import { ChatMessage } from "@/components/chat-message";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";

interface CodexChatPageProps {
  params: {
    chatId: string;
  };
}

interface Message {
  role: "user" | "assistant";
  content: string;
  model?: string;
  hasSources?: boolean;
}

export default function CodexAgentChatPage({ params }: CodexChatPageProps) {
  const searchParams = useSearchParams();
  const prompt = searchParams.get("prompt") || "Build a new feature";
  const [messages, setMessages] = useState<Message[]>([]);

  useEffect(() => {
    const userMessage: Message = {
      role: "user",
      content: prompt,
    };

    const aiResponse: Message = {
      role: "assistant",
      content:
        `I'll help you ${prompt.toLowerCase()}. Let me analyze the requirements and create a solution for you.\n\n` +
        "First, I'll examine the current codebase structure and identify the best approach. Then I'll implement the necessary changes while following best practices and maintaining code quality.\n\n" +
        "The implementation will include proper error handling, type safety, and comprehensive testing to ensure everything works as expected.",
      model: "GPT-5.1",
    };

    setMessages([userMessage, aiResponse]);
  }, [prompt]);

  const handleSubmit = (content: string) => {
    const newUserMessage: Message = { role: "user", content };
    setMessages((prev) => [...prev, newUserMessage]);

    setTimeout(() => {
      const demoAssistantMessage: Message = {
        role: "assistant",
        content: `This is a demo response to: "${content}". In a real application, this would be generated by the AI model with specific code changes and implementation details.`,
        model: "GPT-5.1",
      };
      setMessages((prev) => [...prev, demoAssistantMessage]);
    }, 500);
  };

  return (
    <div className="flex h-screen flex-col bg-black dark">
      <div className="flex h-[53px] items-center justify-between border-b border-zinc-800 bg-black px-4">
        <div className="flex items-center gap-3">
          <Link href="/agents/codex">
            <Button variant="ghost" size="icon" className="h-8 w-8 text-zinc-400 hover:text-zinc-100">
              <ArrowLeft className="h-4 w-4" />
            </Button>
          </Link>
          <div>
            <h1 className="text-sm font-medium text-zinc-100 line-clamp-1">{prompt}</h1>
            <p className="text-xs text-zinc-500">
              {new Date().toLocaleDateString("en-US", { month: "short", day: "numeric" })}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <Button variant="ghost" size="sm" className="h-8 gap-2 text-xs text-zinc-400 hover:text-zinc-100">
            <Archive className="h-3.5 w-3.5" />
            <span className="hidden sm:inline">Archive</span>
          </Button>
          <Button variant="ghost" size="sm" className="h-8 gap-2 text-xs text-zinc-400 hover:text-zinc-100">
            <Share className="h-3.5 w-3.5" />
            <span className="hidden sm:inline">Share</span>
          </Button>
        </div>
      </div>

      <ScrollArea className="flex-1">
        <div className="py-4">
          <div className="w-full px-4 sm:px-6 lg:px-12 space-y-4">
            {messages.map((message, index) => (
              <ChatMessage key={`${params.chatId}-${index}`} {...message} />
            ))}
          </div>
        </div>
      </ScrollArea>

      <div className="border-t border-zinc-800 bg-black px-4 sm:px-6 lg:px-12 py-3 sm:py-4">
        <div className="mx-auto w-full max-w-3xl">
          <ChatComposer
            placeholder="Request changes or ask a question"
            onSubmit={handleSubmit}
          />
        </div>
      </div>
    </div>
  );
}
