'use client'

import { useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { ChatSidebar } from '@/components/chat-sidebar'
import { Button } from '@/components/ui/button'
import { ChatMessage } from '@/components/chat-message'
import { ChatComposer } from '@/components/chat-composer'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Plus, Mic, Send } from 'lucide-react'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'

interface ProjectChat {
  id: string
  title: string
  preview: string
  date: string
}

interface Message {
  role: 'user' | 'assistant'
  content: string
  model?: string
  hasSources?: boolean
}

export default function ProjectPage() {
  const params = useParams()
  const router = useRouter()
  const projectId = params.id as string
  const [isSidebarOpen, setIsSidebarOpen] = useState(true)
  const [currentModel, setCurrentModel] = useState('GPT-4')
  const [selectedChatId, setSelectedChatId] = useState('')
  const [hasStartedChat, setHasStartedChat] = useState(false)
  const [messages, setMessages] = useState<Message[]>([])

  // Mock project data
  const projectName = 'Skylar LLM Client'
  const projectIcon = '💬'
  const projectChats: ProjectChat[] = [
    { id: '1', title: 'Unique features recap', preview: 'ok wait. we might have more info to this issue...', date: 'Nov 18' },
    { id: '2', title: 'Sources tab issue', preview: 'maybe your mis understand what i want...', date: 'Nov 17' },
    { id: '3', title: 'Marketing LLM Client', preview: 'perfect. so here is how we will set the agent up...', date: 'Nov 17' },
    { id: '4', title: 'Parsing citations in streaming', preview: '', date: 'Nov 17' },
    { id: '5', title: 'Fastest ChatGPT model', preview: 'will there be a 5.1 nano? also, how is nano...', date: 'Nov 16' },
  ]

  const handleSubmit = (message: string) => {
    const newUserMessage: Message = { role: 'user', content: message }
    const demoAssistantMessage: Message = { 
      role: 'assistant', 
      content: `This is a demo response in the project. In a real application, this would be generated by the AI model.`,
      model: currentModel
    }

    setMessages(prev => [...prev, newUserMessage, demoAssistantMessage])
    setHasStartedChat(true)
  }

  const handleChatSelect = (chatId: string) => {
    setSelectedChatId(chatId)
    setHasStartedChat(true)
    // Load mock messages for the selected chat
    setMessages([
      { role: 'user', content: 'How do I implement this feature?' },
      { role: 'assistant', content: 'I can help you implement that feature. Here\'s what you need to do...', model: 'GPT-4' }
    ])
  }

  const handleNewChat = () => {
    router.push('/chat')
  }

  const handleProjectSelect = (id: string) => {
    router.push(`/project/${id}`)
  }

  const handleNewProject = () => {
    router.push('/project/new')
  }

  return (
    <div className="flex h-screen overflow-hidden dark">
      <ChatSidebar 
        isOpen={isSidebarOpen} 
        onToggle={() => setIsSidebarOpen(!isSidebarOpen)}
        currentModel={currentModel}
        onModelSelect={setCurrentModel}
        selectedChatId={selectedChatId}
        onChatSelect={() => router.push('/chat')}
        onNewChat={handleNewChat}
        onNewProject={handleNewProject}
        onProjectSelect={handleProjectSelect}
        selectedProjectId={projectId}
      />

      <div className="flex flex-1 flex-col">
        {!hasStartedChat ? (
          // Project overview with vertical chat list
          <div className="flex flex-1 flex-col items-center justify-center p-8">
            <div className="w-full max-w-3xl space-y-8">
              <div className="flex items-center justify-center gap-3">
                <span className="text-4xl">{projectIcon}</span>
                <h1 className="text-3xl font-semibold text-foreground">{projectName}</h1>
              </div>

              <div className="space-y-2">
                <div className="relative">
                  <input
                    type="text"
                    placeholder={`New chat in ${projectName}`}
                    className="w-full rounded-full border border-border bg-background px-6 py-4 pr-24 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                    onKeyDown={(e) => {
                      if (e.key === 'Enter' && e.currentTarget.value.trim()) {
                        handleSubmit(e.currentTarget.value)
                        e.currentTarget.value = ''
                      }
                    }}
                  />
                  <div className="absolute right-2 top-1/2 flex -translate-y-1/2 items-center gap-2">
                    <Button variant="ghost" size="icon" className="h-8 w-8 rounded-full">
                      <Mic className="h-4 w-4" />
                    </Button>
                    <Button size="icon" className="h-8 w-8 rounded-full bg-white text-black hover:bg-white/90">
                      <Send className="h-4 w-4" />
                    </Button>
                  </div>
                </div>

                <div className="flex justify-end">
                  <Button variant="ghost" size="sm" className="gap-2 text-sm text-muted-foreground">
                    <Plus className="h-4 w-4" />
                    Add files
                  </Button>
                </div>
              </div>

              <div className="space-y-3">
                {projectChats.map((chat) => (
                  <button
                    key={chat.id}
                    onClick={() => handleChatSelect(chat.id)}
                    className="w-full rounded-lg border border-border bg-card p-4 text-left transition-colors hover:bg-accent"
                  >
                    <div className="flex items-start justify-between gap-4">
                      <div className="flex-1 space-y-1">
                        <h3 className="font-medium text-foreground">{chat.title}</h3>
                        {chat.preview && (
                          <p className="text-sm text-muted-foreground line-clamp-2">{chat.preview}</p>
                        )}
                      </div>
                      <span className="text-xs text-muted-foreground whitespace-nowrap">{chat.date}</span>
                    </div>
                  </button>
                ))}
              </div>
            </div>
          </div>
        ) : (
          // Normal chat view when user types
          <>
            <div className="flex h-[53px] items-center justify-between border-b border-border px-4">
              <div className="flex items-center gap-2">
                {!isSidebarOpen && (
                  <Button
                    variant="ghost"
                    size="icon"
                    onClick={() => setIsSidebarOpen(true)}
                    className="h-8 w-8"
                  >
                    <svg className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                      <rect x="3" y="3" width="18" height="18" rx="2" strokeWidth="2"/>
                      <line x1="9" y1="3" x2="9" y2="21" strokeWidth="2"/>
                    </svg>
                  </Button>
                )}
                <Select value={currentModel} onValueChange={setCurrentModel}>
                  <SelectTrigger className="h-9 w-auto gap-1 border-0 px-2 focus:ring-0">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="GPT-4">GPT-4</SelectItem>
                    <SelectItem value="GPT-4 Turbo">GPT-4 Turbo</SelectItem>
                    <SelectItem value="GPT-3.5">GPT-3.5</SelectItem>
                    <SelectItem value="Claude 3">Claude 3</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              
              <div className="flex items-center gap-2">
                <Button variant="ghost" size="sm" className="gap-2 text-muted-foreground">
                  <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
                  </svg>
                  Share
                </Button>
                <Button variant="ghost" size="sm" className="gap-2 text-muted-foreground">
                  <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4" />
                  </svg>
                  Archive
                </Button>
              </div>
            </div>

            <ScrollArea className="flex-1">
              <div className="py-4">
                {messages.map((message, index) => (
                  <ChatMessage key={index} {...message} />
                ))}
              </div>
            </ScrollArea>

            <ChatComposer onSubmit={handleSubmit} />
          </>
        )}
      </div>
    </div>
  )
}
