'use client'

import { useState, useEffect } from 'react'
import { useSearchParams, useRouter } from 'next/navigation'
import { ChatSidebar } from '@/components/chat-sidebar'
import { ChatMessage } from '@/components/chat-message'
import { ChatComposer } from '@/components/chat-composer'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Button } from '@/components/ui/button'
import { Menu, PanelLeft } from 'lucide-react'
import { SettingsModal } from '@/components/settings-modal'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'

interface Message {
  role: 'user' | 'assistant'
  content: string
  model?: string
  hasSources?: boolean
}

interface ChatData {
  id: string
  title: string
  timestamp: string
  messages: Message[]
}

const initialChats: ChatData[] = []

export default function ChatPage() {
  const router = useRouter()
  const [isSidebarOpen, setIsSidebarOpen] = useState(false)
  const [currentModel, setCurrentModel] = useState('GPT-4')
  const [chats, setChats] = useState<ChatData[]>(initialChats)
  const searchParams = useSearchParams()
  const chatIdFromUrl = searchParams.get('id')
  const [selectedChatId, setSelectedChatId] = useState(chatIdFromUrl || '')
  const [selectedProjectId, setSelectedProjectId] = useState('')
  const [isSettingsOpen, setIsSettingsOpen] = useState(false)

  useEffect(() => {
    const handleResize = () => {
      if (window.innerWidth >= 1024) {
        setIsSidebarOpen(true)
      } else {
        setIsSidebarOpen(false)
      }
    }
    
    handleResize()
    window.addEventListener('resize', handleResize)
    return () => window.removeEventListener('resize', handleResize)
  }, [])

  const currentChat = chats.find(c => c.id === selectedChatId)
  const messages = currentChat?.messages || []

  const handleSubmit = (message: string) => {
    const newUserMessage: Message = { role: 'user', content: message }
    const demoAssistantMessage: Message = { 
      role: 'assistant', 
      content: `This is a demo response to: "${message}". In a real application, this would be generated by the AI model.`,
      model: currentModel
    }

    // If no chat is selected, create a new "Demo Chat"
    if (!selectedChatId) {
      const newChatId = Date.now().toString()
      const newChat: ChatData = {
        id: newChatId,
        title: 'Demo Chat',
        timestamp: 'Just now',
        messages: [newUserMessage, demoAssistantMessage]
      }
      setChats(prevChats => [newChat, ...prevChats])
      setSelectedChatId(newChatId)
    } else {
      // Update existing chat
      setChats(prevChats => {
        const updatedChats = prevChats.map(chat => {
          if (chat.id === selectedChatId) {
            return {
              ...chat,
              messages: [...chat.messages, newUserMessage, demoAssistantMessage],
              timestamp: 'Just now',
              title: chat.messages.length === 0 ? message.slice(0, 50) : chat.title
            }
          }
          return chat
        })

        // Move updated chat to top
        const currentChatIndex = updatedChats.findIndex(c => c.id === selectedChatId)
        if (currentChatIndex > 0) {
          const currentChat = updatedChats.splice(currentChatIndex, 1)[0]
          updatedChats.unshift(currentChat)
        }

        return updatedChats
      })
    }
  }

  const handleChatSelect = (id: string) => {
    setSelectedChatId(id)
  }

  const handleNewChat = () => {
    setSelectedChatId('')
  }

  const handleProjectSelect = (id: string) => {
    router.push(`/project/${id}`)
  }

  const handleNewProject = () => {
    router.push('/project/new')
  }

  const conversations = chats.map(chat => ({
    id: chat.id,
    title: chat.title,
    timestamp: chat.timestamp
  }))

  return (
    <div className="flex h-screen overflow-hidden dark">
      <ChatSidebar 
        isOpen={isSidebarOpen} 
        onToggle={() => setIsSidebarOpen(!isSidebarOpen)}
        currentModel={currentModel}
        onModelSelect={setCurrentModel}
        selectedChatId={selectedChatId}
        conversations={conversations}
        onChatSelect={handleChatSelect}
        onNewChat={handleNewChat}
        onNewProject={handleNewProject}
        onProjectSelect={handleProjectSelect}
        selectedProjectId={selectedProjectId}
        onSettingsOpen={() => setIsSettingsOpen(true)}
      />
      
      <div className="flex flex-1 flex-col w-full min-w-0">
        <div className="flex h-[53px] items-center justify-between border-b border-border px-3 lg:px-4">
          <div className="flex items-center gap-2 min-w-0">
            {/* Mobile sidebar toggle */}
            <Button
              variant="ghost"
              size="icon"
              className="h-9 w-9 lg:hidden"
              onClick={() => setIsSidebarOpen(!isSidebarOpen)}
            >
              <Menu className="h-4 w-4" />
            </Button>

            <Select value={currentModel} onValueChange={setCurrentModel}>
              <SelectTrigger className="h-9 w-auto gap-1 border-0 px-2 focus:ring-0">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="GPT-4">GPT-5.1</SelectItem>
                <SelectItem value="GPT-4 Turbo">GPT-4 Turbo</SelectItem>
                <SelectItem value="GPT-3.5">GPT-3.5</SelectItem>
                <SelectItem value="Claude 3">Claude 3</SelectItem>
              </SelectContent>
            </Select>
          </div>
          
          <div className="hidden sm:flex items-center gap-2">
            <Button variant="ghost" size="sm" className="gap-2 text-muted-foreground">
              <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
              </svg>
              <span className="hidden md:inline">Share</span>
            </Button>
            <Button variant="ghost" size="sm" className="gap-2 text-muted-foreground">
              <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4" />
              </svg>
              <span className="hidden md:inline">Archive</span>
            </Button>
          </div>
        </div>
        
        {!selectedChatId || messages.length === 0 ? (
          <div className="flex flex-1 items-center justify-center px-4 overflow-hidden">
            <div className="text-center">
              <h2 className="text-xl sm:text-2xl font-semibold text-foreground mb-2">Where should we begin?</h2>
            </div>
          </div>
        ) : (
          <ScrollArea className="flex-1 overflow-auto">
            <div className="py-4 pb-24 sm:pb-4">
              {messages.map((message, index) => (
                <ChatMessage key={index} {...message} />
              ))}
            </div>
          </ScrollArea>
        )}

        {/* Composer is now fixed to bottom on mobile */}
        <div className="fixed bottom-0 left-0 right-0 lg:relative lg:bottom-auto lg:left-auto lg:right-auto">
          <ChatComposer onSubmit={handleSubmit} />
        </div>
      </div>

      {/* Render settings modal at page level so it centers over entire page */}
      <SettingsModal isOpen={isSettingsOpen} onClose={() => setIsSettingsOpen(false)} />
    </div>
  )
}
